name: dpboss
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # for getting version 
  package_info_plus: ^3.0.3

  google_fonts: ^4.0.3
  page_transition: ^2.0.9
  persistent_bottom_nav_bar: any

  # for webscraping
  html: ^0.15.2
  http: ^0.13.5
  beautiful_soup_dart: ^0.3.0
  webview_flutter: ^4.0.7
  # state mangment 
  provider: ^6.0.5
  # for icons
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  cloud_firestore: ^4.5.0
  flutter_local_notifications: ^13.0.0
  firebase_auth: ^4.4.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Dpboss_Net/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21  

flutter:
  uses-material-design: true

  assets: 
    - assets/Dpboss_Net/
  fonts:
    - family: Howell Rode
      fonts:
        - asset: assets/fonts/Howell Rode.ttf 

    - family: Alibaba Sans
      fonts:
        - asset: assets/fonts/AlibabaSans-Regular.ttf 